Repository upbound/crossplane, pull requests merged in 2022-09, with the labels that each got.

#56 Sync release-1.7 with upstream
  apis/apiextensions/v1alpha1/revision_types.go
  apis/apiextensions/v1alpha1/zz_generated.deepcopy.go
  cluster/charts/crossplane/templates/clusterrole.yaml
  cluster/charts/crossplane/templates/deployment.yaml
  cluster/crds/apiextensions.crossplane.io_compositionrevisions.yaml
  docs/cloud-providers/aws/aws-provider.md
  docs/cloud-providers/gcp/gcp-provider.md
  docs/concepts/providers.md
  docs/faqs/related_projects.md
  docs/getting-started/create-configuration.md
  docs/getting-started/install-configure.md
  docs/guides/multi-tenant.md
  docs/guides/self-signed-ca-certs.md
  docs/reference/composition.md
  docs/snippets/configure/aws/setup.sh
  docs/snippets/package/aws-with-vpc/crossplane.yaml
  docs/snippets/package/aws-with-vpc/definition.yaml
  docs/snippets/package/aws/crossplane.yaml
  docs/snippets/package/aws/definition.yaml
  docs/snippets/package/azure/composition.yaml
  docs/snippets/package/azure/crossplane.yaml
  docs/snippets/package/azure/definition.yaml
  docs/snippets/package/gcp/crossplane.yaml
  docs/snippets/package/gcp/definition.yaml
  internal/controller/apiextensions/composite/revision.go
  internal/controller/apiextensions/composite/revision_test.go
  internal/controller/apiextensions/composition/revision.go
  internal/controller/apiextensions/composition/revision_test.go
  internal/controller/pkg/resolver/reconciler_test.go
  internal/controller/pkg/revision/dependency.go
  internal/controller/pkg/revision/dependency_test.go
  internal/dag/dag.go
  internal/dag/dag_test.go
  internal/dag/fake/mocks.go
  internal/xpkg/fetch.go
Labels: size/XL

#58 Sync release-1.9 with upstream
  cluster/charts/crossplane/templates/clusterrole.yaml
  docs/cloud-providers/aws/aws-provider.md
  docs/cloud-providers/gcp/gcp-provider.md
  docs/concepts/providers.md
  docs/faqs/related_projects.md
  docs/getting-started/create-configuration.md
  docs/getting-started/install-configure.md
  docs/guides/multi-tenant.md
  docs/guides/self-signed-ca-certs.md
  docs/reference/composition.md
  docs/snippets/configure/aws/setup.sh
  docs/snippets/package/aws-with-vpc/crossplane.yaml
  docs/snippets/package/aws-with-vpc/definition.yaml
  docs/snippets/package/aws/crossplane.yaml
  docs/snippets/package/aws/definition.yaml
  docs/snippets/package/azure/composition.yaml
  docs/snippets/package/azure/crossplane.yaml
  docs/snippets/package/azure/definition.yaml
  docs/snippets/package/gcp/crossplane.yaml
  docs/snippets/package/gcp/definition.yaml
  internal/controller/pkg/resolver/reconciler_test.go
  internal/controller/pkg/revision/dependency.go
  internal/controller/pkg/revision/dependency_test.go
  internal/dag/dag.go
  internal/dag/dag_test.go
  internal/dag/fake/mocks.go
  internal/xpkg/fetch.go
Labels: size/L

#61 [release-1.9] Fetch package pull secrets from Crossplane SA and propagate to Provider Deployments
  cluster/charts/crossplane/templates/deployment.yaml
  cmd/crossplane/core/core.go
  internal/controller/pkg/controller/options.go
  internal/controller/pkg/manager/reconciler.go
  internal/controller/pkg/resolver/reconciler.go
  internal/controller/pkg/revision/deployment.go
  internal/controller/pkg/revision/deployment_test.go
  internal/controller/pkg/revision/hook.go
  internal/controller/pkg/revision/hook_test.go
  internal/controller/pkg/revision/reconciler.go
  internal/xpkg/fetch.go
Labels: size/L

#60 [release-1.8] Fetch package pull secrets from Crossplane SA and propagate to Provider Deployments
  cluster/charts/crossplane/templates/deployment.yaml
  cmd/crossplane/core/core.go
  internal/controller/pkg/controller/options.go
  internal/controller/pkg/manager/reconciler.go
  internal/controller/pkg/resolver/reconciler.go
  internal/controller/pkg/revision/deployment.go
  internal/controller/pkg/revision/deployment_test.go
  internal/controller/pkg/revision/hook.go
  internal/controller/pkg/revision/hook_test.go
  internal/controller/pkg/revision/reconciler.go
  internal/xpkg/fetch.go
Labels: size/L

#59 [release-1.7] Fetch package pull secrets from Crossplane SA and propagate to Provider Deployments
  cluster/charts/crossplane/templates/deployment.yaml
  cmd/crossplane/core/core.go
  internal/controller/pkg/controller/options.go
  internal/controller/pkg/manager/reconciler.go
  internal/controller/pkg/resolver/reconciler.go
  internal/controller/pkg/revision/deployment.go
  internal/controller/pkg/revision/deployment_test.go
  internal/controller/pkg/revision/hook.go
  internal/controller/pkg/revision/hook_test.go
  internal/controller/pkg/revision/reconciler.go
  internal/xpkg/fetch.go
Labels: size/L

#62 Drop configuration publishing workflows
  .github/workflows/configurations.yml
Labels: size/L

#63 Cherry-pick the ability to disable clusterrole aggregation
  cluster/charts/crossplane/templates/clusterrole.yaml
Labels: size/XS
